services:
  db:
    image: docker.io/library/postgres:15  # Adicionado docker.io/library/
    container_name: cep-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cepdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  wiremock:
    image: docker.io/wiremock/wiremock:latest
    container_name: cep-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./src/main/resources/wiremock:/home/wiremock