spring.application.name=cepapi
# URL de conexão para o Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/cepdb
spring.datasource.username=user
spring.datasource.password=password

# Define o driver correto (Isso resolve o seu erro)
spring.datasource.driver-class-name=org.postgresql.Driver

# Ajuste do Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# URL do WireMock (Docker)
cep.api.url=http://localhost:8081/cep