spring.application.name=cepapi

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cepdb}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

cep.api.url=${CEP_API_URL:http://localhost:8081/cep}

server.port=${APP_PORT:8080}

spring.security.user.name=${API_USER:admin}
spring.security.user.password=${API_PASSWORD:admin123}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never